import type { Metadata } from 'next';
import './globals.css';
import LayoutWrapper from '@/components/utils/LayoutWrapper';
import { Toaster } from 'react-hot-toast';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// ${geistSans.variable} ${geistMono.variable} 

export const metadata: Metadata = {
  title: 'Mohanteja | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body
        className={`font-geist text-text antialiased`}
      >
        <LayoutWrapper>
          <Toaster position='top-right' />
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
