import type { Metadata } from 'next';
import './globals.css';
import LayoutWrapper from '@/components/utils/LayoutWrapper';
import { Toaster } from 'react-hot-toast';
import { Manrope, Space_Grotesk } from 'next/font/google';
import localFont from 'next/font/local';

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
});

const geistMono = localFont({
  src: '../public/fonts/GeistFam/Geist_Mono/static/GeistMono-Regular.ttf',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Mohanteja | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body
        className={`${manrope.variable} ${spaceGrotesk.variable} ${geistMono.variable} font-sans text-text antialiased bg-ink`}
      >
        <LayoutWrapper>
          <Toaster position='top-right' />
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
